### ISSUE TITLE
Wrong return type read_word_data()

### ISSUE THREAD

**Issue by Rotzbua** [MomsFriendlyRobotCompany/fake_rpi#12]
## Environment

* Raspberry pi 4
* raspian buster
* python 3.7
* latest fake_rpi

## Description

Function returns wrong type. List of integer instead of an integer. **Maybe there are more mismatches.**

https://github.com/MomsFriendlyRobotCompany/fake_rpi/blob/eb2f640f19f74db9082bfbf8aed524e3ccba6d4f/fake_rpi/smbus/smbus.py#L29-L31

## Observed

```bash
value
[185, 185]
type
<class 'list'>
```

## Expected
```bash
value
65535
type
<class 'int'>
```

## Testcode

```python
import sys
import fake_rpi

sys.modules['RPi'] = fake_rpi.RPi  # Fake RPi (GPIO)
sys.modules['smbus'] = fake_rpi.smbus  # Fake smbus (I2C)

import smbus

if __name__ == "__main__":
    bus = smbus.SMBus(1)

    value = bus.read_word_data(0x01, 1 << 1)
    print("value")
    print(value)
    print("type")
    print(type(value))
```

**Comment by walchko** [comment]
So I guess it depends on how you think a word gets reported to you. I2C sends bytes (8bits) across the wire. If I ask for a word, then I get 2 bytes (see picture below). So that is how I wrote the function.

![](https://www.solitontech.com/wp-content/uploads/2018/08/I2C-Read-Block-Format.png)

Generally, if you were writing a hardware driver, talking to I2C, you would just get an array of bytes you have to break up and make sense of. Not sure what the right answer is ... but let me think about it.

**Comment by Rotzbua** [comment]
@walchko The picture shows the general i2c protocol. But it seems that the raspberry uses a different interface as I mentioned above. For my specific environment setup the raspberry returned it as a word. Maybe there are differences in OS, python and i2c library versions.

**Comment by walchko** [comment]
sorry, what library are you using to read the i2c bus?

**Comment by walchko** [comment]
I will change it ... looking at some other libraries, it probably makes more sense. Thanks!
