### ISSUE TITLE
Does this support gpiozero?

### ISSUE THREAD

**Issue by pfmephisto** [MomsFriendlyRobotCompany/fake_rpi#15]
Great project, guys.

Should this also be working with gpiozero or only RPi.GPIO?
I'm trying to set up travis-ci and am having the test fail.

If I´m using gpiozero the error I get is:
`gpiozero.exc.PinUnknownPi: unable to locate Pi revision in /proc/device-tree or /proc/cpuinfo`
and with RPi.GPIO,
travis doesn't seem to be able to find and install the library in the first place.

Running it locally on a RaspberryPi 2 Model B everything seems to be working well with both gpiozero and  RPi.GPIO. _(without fake_rpi)_

I was hoping that you might have some pointers, since it seems like this was one of the intended uses of the project.

**Comment by walchko** [comment]
Hello, I am confused. The whole point of this is to mimic some of the interfaces a pi has on a computer for testing and development. If you have a pi (2,3,4, zero) and are developing directly on it, then this isn't useful to you. If you have a laptop and are developing for the pi, then you can fake your code out to think it is running on the pi. Please note, it doesn't mimic a whole pi, but a few buses and things not typically found on a laptop/personal computer to a limited extent.

I don't understand the travis comment, just install the library with pip in your travis.yml file and you have it. Infact, this is really useful for travis, because you don't have access to those buses in the virtual environment.

**Comment by pfmephisto** [comment]
Thanks for the answer @walchko,
Maybe I was a bit too brief in my description. So I've been writing a bot that's supposed to be running on a raspberryPi [Link](https://github.com/pfmephisto/telegram-coffee-bot). So far I have been developing it on my own computer and then test running it on the pi.
So now I decided to throw it on GitHub to give some friends the opportunity to pich in.

I also stumbled over travis and thought I'd give it a try since the whole project is manly for fun and getting familiar with a couple of new things.
I realise that travis might not be the ideal platform for testing anything that's supposed to go on a rpi but after finding your library I thought I'd give it a chance anyway. 

The comment about the library was more in regards to you referring to RPi.GPIO in your usage instructions and I haven't gotten that to install properly on travis. So far I tried including it in my python environment  and using apt-get in the travis.yml. Haven't tried pip so far but will do this next.

If I don't get it to run on travis it's not that important, I just thought it would be a neat thing.
